// Generated from figma tokens. Do not edit directly.

export const THEME_FONTS_TRILOGY = {
  "sizeTitle1": 28,
  "lineHeightTitle1": 36,
  "fontTitle1": "Bouygues Read",
  "fontWeightTitle1": 400,
  "sizeTitle2": 24,
  "lineHeightTitle2": 30,
  "fontTitle2": "Bouygues Read",
  "fontWeightTitle2": 400,
  "sizeTitle3": 22,
  "lineHeightTitle3": 28,
  "fontTitle3": "Bouygues Speak Corpo",
  "fontWeightTitle3": 700,
  "title4Size": 20,
  "lineHeightTitle4": 26,
  "fontTitle4": "Bouygues Speak Corpo",
  "fontWeightTitle4": 700,
  "sizeTitle5": 18,
  "lineHeightTitle5": 22,
  "fontTitle5": "Bouygues Speak Corpo",
  "fontWeightTitle5": 700,
  "sizeTitle6": 16,
  "lineHeightTitle6": 20,
  "fontTitle6": "Bouygues Speak Corpo",
  "fontWeightTitle6": 700,
  "body1Size": 16,
  "body1LineHeight": 24,
  "fontBody1": "Bouygues Speak Corpo",
  "fontWeightBody1": 400,
  "tokenfontBody1BoldSize": 16,
  "tokenfontBody1BoldLineHeight": 24,
  "tokenfontBody1BoldFontBody1Bold": "Bouygues Speak Corpo",
  "fontWeightBody1Bold": 600,
  "body2Size": 14,
  "body2LineHeight": 22,
  "fontBody2": "Bouygues Speak Corpo",
  "fontWeightBody2": 400,
  "tokenfontBody2BoldSize": 14,
  "tokenfontBody2BoldLineHeight": 22,
  "tokenfontBody2BoldFontBody2Bold": "Bouygues Speak Corpo",
  "fontWeightBody2Bold": 600,
  "body3Size": 12,
  "body3LineHeight": 18,
  "fontBody3": "Bouygues Speak Corpo",
  "fontWeightBody3": 400,
  "tokenfontBody3BoldSize": 12,
  "tokenfontBody3BoldLineHeight": 18,
  "tokenfontBody3BoldFontBody3Bold": "Bouygues Speak Corpo",
  "fontWeightBody3Bold": 600,
  "body4Size": 10,
  "body4LineHeight": 16,
  "fontBody4": "Bouygues Speak Corpo",
  "fontWeightBody4": 400,
  "tokenfontBody4BoldSize": 10,
  "tokenfontBody4BoldLineHeight": 16,
  "tokenfontBody4BoldFontBody4Bold": "Bouygues Speak Corpo",
  "fontWeightBody4Bold": 600,
} as const
