// Generated from figma tokens. Do not edit directly.

export const THEME_TRILOGY = {
  colors: {
    light: {
      "border": "#CCDEEB",
      "borderSelected": "#062B3F",
      "borderInactive": "#7F949F",
      "borderAccent": "#CC4E0A",
      "borderDisabled": "#818283",
      "borderInverse": "#FFFFFF",
      "borderSuccess": "#267C51",
      "borderWarning": "#F6BB33",
      "borderError": "#D42D02",
      "borderInformation": "#00BCDA",
      "tokenborderBrand": "#CCF2F8",
      "borderWidthMd": 2,
      "borderWidthSm": 1,
      "tokenborderWidthMd": 2,
      "tokenborderWidthLg": 3,
      "background": "#EFF2F8",
      "bgPrimary": "#FFFFFF",
      "bgPrimarySubtle": "#F8F9FA",
      "bgSecondary": "#062B3F",
      "bgSecondarySubtle": "#FFFFFF",
      "bgSuccess": "#267C51",
      "bgSuccessSubtle": "#E3F1E2",
      "bgWarning": "#F6BB33",
      "bgWarningSubtle": "#FAF2E2",
      "bgError": "#D42D02",
      "bgErrorSubtle": "#F6E4E4",
      "bgInformation": "#00BCDA",
      "bgInformationSubtle": "#E9F9FC",
      "bgSelected": "#062B3F",
      "bgSelectedHover": "#052739",
      "tokenbackgroundSelectedPressed": "#041F2D",
      "bgDisabled": "#F8F9FA",
      "bgInactive": "#9BAAB5",
      "bgAccent": "#CC4E0A",
      "bgAccentSubtle": "#FAEDE7",
      "bgBrand": "#CCF2F8",
      "bgBrandSubtle": "#E8F6F8",
      "icon": "#062B3F",
      "iconSelected": "#062B3F",
      "iconDisabled": "#818283",
      "iconAccent": "#CC4E0A",
      "iconInverse": "#FFFFFF",
      "iconSuccess": "#267C51",
      "iconWarning": "#F6BB33",
      "iconError": "#D42D02",
      "iconInformation": "#00BCDA",
      "iconBrand": "#CCF2F8",
      "iconSizeXs": 16,
      "iconSizeSm": 20,
      "iconSizeMd": 32,
      "iconSizeLg": 66,
      "textLink": "#062B3F",
      "textLinkHover": "#041F2D",
      "textLinkVisited": "#041F2D",
      "textSuccess": "#267C51",
      "textWarning": "#F6BB33",
      "textError": "#D42D02",
      "textInformation": "#00BCDA",
      "textPrimary": "#062B3F",
      "textSecondary": "#607A8D",
      "textPlaceholder": "#607A8D",
      "textSelected": "#062B3F",
      "textInverse": "#FFFFFF",
      "textAccent": "#CC4E0A",
      "textDisabled": "#818283",
      "textBrand": "#CCF2F8",
      "btnBgPrimary": "#062B3F",
      "btnBgPrimaryHover": "#052739",
      "btnBgPrimaryPressed": "#041F2D",
      "btnBgAccent": "#CC4E0A",
      "btnBgAccentHover": "#BA4709",
      "btnBgAccentPressed": "#913707",
      "btnTextAccent": "#FFFFFF",
      "btnBgSecondary": "#FFFFFF",
      "btnBgSecondaryHover": "#F8F9FA",
      "btnBgSecondaryPressed": "#F5F6F8",
      "btnBorderSecondary": "#CCDEEB",
      "btnTextPrimary": "#FFFFFF",
      "btnTextSecondary": "#062B3F",
      "btnBgGhost": "#000000",
      "btnBgGhostHover": "#EFF2F8",
      "btnBgGhostPressed": "#CCDEEB",
      "btnTextGhost": "#062B3F",
      "btnBgDisabled": "#F8F9FA",
      "btnTextDisabled": "#818283",
      "layer": "#FFFFFF",
      "bgOverlay": "#062B3F",
      "popover": "#062B3F",
      "inputHover": "#EFF2F8",
      "inputBg": "#FFFFFF",
      "inputPressed": "#CCDEEB",
      "focusBorder": "#062B3F",
      "focusRingWidth": 2,
      "ringOffset": 2,
    },
    dark: {
      "border": "#CCDEEB",
      "borderSelected": "#062B3F",
      "borderInactive": "#7F949F",
      "borderAccent": "#CC4E0A",
      "borderDisabled": "#818283",
      "borderInverse": "#FFFFFF",
      "borderSuccess": "#267C51",
      "borderWarning": "#F6BB33",
      "borderError": "#D42D02",
      "borderInformation": "#00BCDA",
      "tokenborderBrand": "#CCF2F8",
      "borderWidthMd": 2,
      "borderWidthSm": 1,
      "tokenborderWidthMd": 2,
      "tokenborderWidthLg": 3,
      "background": "#EFF2F8",
      "bgPrimary": "#FFFFFF",
      "bgPrimarySubtle": "#F8F9FA",
      "bgSecondary": "#062B3F",
      "bgSecondarySubtle": "#FFFFFF",
      "bgSuccess": "#267C51",
      "bgSuccessSubtle": "#E3F1E2",
      "bgWarning": "#F6BB33",
      "bgWarningSubtle": "#FAF2E2",
      "bgError": "#D42D02",
      "bgErrorSubtle": "#F6E4E4",
      "bgInformation": "#00BCDA",
      "bgInformationSubtle": "#E9F9FC",
      "bgSelected": "#062B3F",
      "bgSelectedHover": "#052739",
      "tokenbackgroundSelectedPressed": "#041F2D",
      "bgDisabled": "#F8F9FA",
      "bgInactive": "#9BAAB5",
      "bgAccent": "#CC4E0A",
      "bgAccentSubtle": "#FAEDE7",
      "bgBrand": "#CCF2F8",
      "bgBrandSubtle": "#E8F6F8",
      "icon": "#062B3F",
      "iconSelected": "#062B3F",
      "iconDisabled": "#818283",
      "iconAccent": "#CC4E0A",
      "iconInverse": "#FFFFFF",
      "iconSuccess": "#267C51",
      "iconWarning": "#F6BB33",
      "iconError": "#D42D02",
      "iconInformation": "#00BCDA",
      "iconBrand": "#CCF2F8",
      "iconSizeXs": 16,
      "iconSizeSm": 20,
      "iconSizeMd": 32,
      "iconSizeLg": 66,
      "textLink": "#062B3F",
      "textLinkHover": "#041F2D",
      "textLinkVisited": "#041F2D",
      "textSuccess": "#267C51",
      "textWarning": "#F6BB33",
      "textError": "#D42D02",
      "textInformation": "#00BCDA",
      "textPrimary": "#062B3F",
      "textSecondary": "#607A8D",
      "textPlaceholder": "#607A8D",
      "textSelected": "#062B3F",
      "textInverse": "#FFFFFF",
      "textAccent": "#CC4E0A",
      "textDisabled": "#818283",
      "textBrand": "#CCF2F8",
      "btnBgPrimary": "#062B3F",
      "btnBgPrimaryHover": "#052739",
      "btnBgPrimaryPressed": "#041F2D",
      "btnBgAccent": "#CC4E0A",
      "btnBgAccentHover": "#BA4709",
      "btnBgAccentPressed": "#913707",
      "btnTextAccent": "#FFFFFF",
      "btnBgSecondary": "#FFFFFF",
      "btnBgSecondaryHover": "#F8F9FA",
      "btnBgSecondaryPressed": "#F5F6F8",
      "btnBorderSecondary": "#CCDEEB",
      "btnTextPrimary": "#FFFFFF",
      "btnTextSecondary": "#062B3F",
      "btnBgGhost": "#000000",
      "btnBgGhostHover": "#EFF2F8",
      "btnBgGhostPressed": "#CCDEEB",
      "btnTextGhost": "#062B3F",
      "btnBgDisabled": "#F8F9FA",
      "btnTextDisabled": "#818283",
      "layer": "#FFFFFF",
      "bgOverlay": "#062B3F",
      "popover": "#062B3F",
      "inputHover": "#EFF2F8",
      "inputBg": "#FFFFFF",
      "inputPressed": "#CCDEEB",
      "focusBorder": "#062B3F",
      "focusRingWidth": 2,
      "ringOffset": 2,
    },
  },
  fonts: {
    "sizeTitle1": 28,
    "lineHeightTitle1": 36,
    "fontTitle1": "Bouygues Read",
    "fontWeightTitle1": 400,
    "sizeTitle2": 24,
    "lineHeightTitle2": 30,
    "fontTitle2": "Bouygues Read",
    "fontWeightTitle2": 400,
    "sizeTitle3": 22,
    "lineHeightTitle3": 28,
    "fontTitle3": "Bouygues Speak Corpo",
    "fontWeightTitle3": 700,
    "title4Size": 20,
    "lineHeightTitle4": 26,
    "fontTitle4": "Bouygues Speak Corpo",
    "fontWeightTitle4": 700,
    "sizeTitle5": 18,
    "lineHeightTitle5": 22,
    "fontTitle5": "Bouygues Speak Corpo",
    "fontWeightTitle5": 700,
    "sizeTitle6": 16,
    "lineHeightTitle6": 20,
    "fontTitle6": "Bouygues Speak Corpo",
    "fontWeightTitle6": 700,
    "body1Size": 16,
    "body1LineHeight": 24,
    "fontBody1": "Bouygues Speak Corpo",
    "fontWeightBody1": 400,
    "tokenfontBody1BoldSize": 16,
    "tokenfontBody1BoldLineHeight": 24,
    "tokenfontBody1BoldFontBody1Bold": "Bouygues Speak Corpo",
    "fontWeightBody1Bold": 600,
    "body2Size": 14,
    "body2LineHeight": 22,
    "fontBody2": "Bouygues Speak Corpo",
    "fontWeightBody2": 400,
    "tokenfontBody2BoldSize": 14,
    "tokenfontBody2BoldLineHeight": 22,
    "tokenfontBody2BoldFontBody2Bold": "Bouygues Speak Corpo",
    "fontWeightBody2Bold": 600,
    "body3Size": 12,
    "body3LineHeight": 18,
    "fontBody3": "Bouygues Speak Corpo",
    "fontWeightBody3": 400,
    "tokenfontBody3BoldSize": 12,
    "tokenfontBody3BoldLineHeight": 18,
    "tokenfontBody3BoldFontBody3Bold": "Bouygues Speak Corpo",
    "fontWeightBody3Bold": 600,
    "body4Size": 10,
    "body4LineHeight": 16,
    "fontBody4": "Bouygues Speak Corpo",
    "fontWeightBody4": 400,
    "tokenfontBody4BoldSize": 10,
    "tokenfontBody4BoldLineHeight": 16,
    "tokenfontBody4BoldFontBody4Bold": "Bouygues Speak Corpo",
    "fontWeightBody4Bold": 600,
  },
  radius: {
    "radiusFull": 9999,
    "radiusLg": 24,
    "radiusMd": 16,
    "radiusSm": 8,
    "radiusXs": 4,
  },
  spacings: {
    "spacingXxl": 40,
    "spacingXl": 32,
    "spacingLg": 24,
    "spacingMd": 16,
    "spacingSm": 12,
    "spacingXs": 8,
    "spacingXxs": 4,
  },
} as const

export const THEME_COLORS_TRILOGY = THEME_TRILOGY.colors
export const THEME_FONTS_TRILOGY = THEME_TRILOGY.fonts
export const THEME_RADIUS_TRILOGY = THEME_TRILOGY.radius
export const THEME_SPACINGS_TRILOGY = THEME_TRILOGY.spacings
