// Generated from figma tokens. Do not edit directly.

export const THEME_TRILOGY = {
  defaultMode: 'light',
  colors: {
    light: {
      background: '#E5EEF3',
      bgPrimary: '#FFFFFF',
      bgPrimarySubtle: '#F7F7F7',
      bgSecondary: '#062B3F',
      bgSecondarySubtle: '#FFFFFF',
      bgSuccess: '#267C51',
      bgSuccessSubtle: '#E7F0EC',
      bgWarning: '#F6BB33',
      bgWarningSubtle: '#F4EFE4',
      bgError: '#D42D02',
      bgErrorSubtle: '#F4E7E3',
      bgInformation: '#00BCDA',
      bgInformationSubtle: '#E3F2F4',
      bgAccent: '#CC4E0A',
      bgAccentSubtle: '#F4EAE4',
      bgBrand: '#CCF2F8',
      bgBrandSubtle: '#E5F1F2',
      inputBgDisabled: '#F7F7F7',
      inputBgDisabledSelected: '#626E81',
      inputBgInactive: '#9BAAB5',
      inputBorderSelected: '#062B3F',
      inputBorderInactive: '#6D8394',
      inputBorderDisabled: '#626E81',
      inputBg: '#FFFFFF',
      inputBgSelected: '#062B3F',
      inputBgSelectedHover: '#042435',
      inputBgSelectedPressed: '#041C29',
      inputBgHover: '#E5EEF3',
      inputBgPressed: '#BBC6CD',
      inputBorderWidthSelected: 2,
      inputBorderWidthUnselected: 1,
      icon: '#062B3F',
      iconSelected: '#062B3F',
      iconDisabled: '#626E81',
      iconAccent: '#CC4E0A',
      iconInverse: '#FFFFFF',
      iconSuccess: '#267C51',
      iconWarning: '#F6BB33',
      iconError: '#D42D02',
      iconInformation: '#00BCDA',
      iconBrand: '#CCF2F8',
      iconSizeXs: 16,
      iconSizeSm: 20,
      iconSizeMd: 32,
      iconSizeLg: 66,
      textLink: '#062B3F',
      textLinkHover: '#041C29',
      textLinkVisited: '#041C29',
      textSuccess: '#267C51',
      textWarning: '#F6BB33',
      textError: '#D42D02',
      textInformation: '#00BCDA',
      textPrimary: '#062B3F',
      textSecondary: '#516B7F',
      textPlaceholder: '#516B7F',
      textSelected: '#062B3F',
      textInverse: '#FFFFFF',
      textAccent: '#CC4E0A',
      textDisabled: '#626E81',
      textBrand: '#CCF2F8',
      btnBgPrimary: '#062B3F',
      btnBgPrimaryHover: '#042435',
      btnTextPrimary: '#FFFFFF',
      btnBorderPrimary: '#062B3F',
      btnBgPrimaryPressed: '#041C29',
      btnBgAccent: '#CC4E0A',
      btnBorderAccent: '#CC4E0A',
      btnBgAccentHover: '#AB3F04',
      btnBgAccentPressed: '#853307',
      btnTextAccent: '#FFFFFF',
      btnBgSecondary: '#FFFFFF',
      btnBgSecondaryHover: '#F7F7F7',
      btnBgSecondaryPressed: '#F2F2F2',
      btnBorderSecondary: '#BBC6CD',
      btnTextSecondary: '#062B3F',
      btnBgGhost: '#FFFFFF',
      btnBgGhostHover: '#E5EEF3',
      btnBorderGhost: '#BBC6CD',
      btnBgGhostPressed: '#BBC6CD',
      btnTextGhost: '#062B3F',
      btnBgDisabled: '#F7F7F7',
      btnTextDisabled: '#626E81',
      border: '#BBC6CD',
      borderAccent: '#CC4E0A',
      borderInverse: '#FFFFFF',
      borderSuccess: '#267C51',
      borderWarning: '#F6BB33',
      borderError: '#D42D02',
      borderInformation: '#00BCDA',
      borderBrand: '#CCF2F8',
      borderWidthSm: 1,
      borderWidthMd: 2,
      borderWidthLg: 3,
      layer: '#FFFFFF',
      bgOverlay: '#062B3F',
      cardBackground: '#FFFFFF',
      popover: '#062B3F',
      focusBorder: '#062B3F',
      focusRingWidth: 1,
      focusRingOffset: 2,
      elevationXsColor: '#040C10',
      elevationXsBlur: 2,
      elevationXsOffsetY: 1,
      elevationSmColor: '#040C10',
      elevationSmBlur: 4,
      elevationSmOffsetY: 2,
      elevationMdColor: '#040C10',
      elevationMdBlur: 8,
      elevationMdOffsetY: 4,
      elevationLgColor: '#040C10',
      elevationLgBlur: 16,
      elevationLgOffsetY: 8,
      elevationXlColor: '#040C10',
      elevationXlBlur: 32,
      elevationXlOffsetY: 12,
      stepBgActive: '#062B3F',
      stepBgDone: '#062B3F',
      stepBgInactive: '#BBC6CD',
      stepBgError: '#D42D02',
      fontFamilyPrimary: 'Bouygues Speak Corpo',
      fontFamilySecondary: 'Bouygues Read',
    },
    dark: {
      background: '#E5EEF3',
      bgPrimary: '#FFFFFF',
      bgPrimarySubtle: '#F7F7F7',
      bgSecondary: '#062B3F',
      bgSecondarySubtle: '#FFFFFF',
      bgSuccess: '#267C51',
      bgSuccessSubtle: '#E7F0EC',
      bgWarning: '#F6BB33',
      bgWarningSubtle: '#F4EFE4',
      bgError: '#D42D02',
      bgErrorSubtle: '#F4E7E3',
      bgInformation: '#00BCDA',
      bgInformationSubtle: '#E3F2F4',
      bgAccent: '#CC4E0A',
      bgAccentSubtle: '#F4EAE4',
      bgBrand: '#CCF2F8',
      bgBrandSubtle: '#E5F1F2',
      inputBgDisabled: '#F7F7F7',
      inputBgDisabledSelected: '#626E81',
      inputBgInactive: '#9BAAB5',
      inputBorderSelected: '#062B3F',
      inputBorderInactive: '#6D8394',
      inputBorderDisabled: '#626E81',
      inputBg: '#FFFFFF',
      inputBgSelected: '#062B3F',
      inputBgSelectedHover: '#042435',
      inputBgSelectedPressed: '#041C29',
      inputBgHover: '#E5EEF3',
      inputBgPressed: '#BBC6CD',
      inputBorderWidthSelected: 2,
      inputBorderWidthUnselected: 1,
      icon: '#062B3F',
      iconSelected: '#062B3F',
      iconDisabled: '#626E81',
      iconAccent: '#CC4E0A',
      iconInverse: '#FFFFFF',
      iconSuccess: '#267C51',
      iconWarning: '#F6BB33',
      iconError: '#D42D02',
      iconInformation: '#00BCDA',
      iconBrand: '#CCF2F8',
      iconSizeXs: 16,
      iconSizeSm: 20,
      iconSizeMd: 32,
      iconSizeLg: 66,
      textLink: '#062B3F',
      textLinkHover: '#041C29',
      textLinkVisited: '#041C29',
      textSuccess: '#267C51',
      textWarning: '#F6BB33',
      textError: '#D42D02',
      textInformation: '#00BCDA',
      textPrimary: '#062B3F',
      textSecondary: '#516B7F',
      textPlaceholder: '#516B7F',
      textSelected: '#062B3F',
      textInverse: '#FFFFFF',
      textAccent: '#CC4E0A',
      textDisabled: '#626E81',
      textBrand: '#CCF2F8',
      btnBgPrimary: '#062B3F',
      btnBgPrimaryHover: '#042435',
      btnTextPrimary: '#FFFFFF',
      btnBorderPrimary: '#062B3F',
      btnBgPrimaryPressed: '#041C29',
      btnBgAccent: '#CC4E0A',
      btnBorderAccent: '#CC4E0A',
      btnBgAccentHover: '#AB3F04',
      btnBgAccentPressed: '#853307',
      btnTextAccent: '#FFFFFF',
      btnBgSecondary: '#FFFFFF',
      btnBgSecondaryHover: '#F7F7F7',
      btnBgSecondaryPressed: '#F2F2F2',
      btnBorderSecondary: '#BBC6CD',
      btnTextSecondary: '#062B3F',
      btnBgGhost: '#FFFFFF',
      btnBgGhostHover: '#E5EEF3',
      btnBorderGhost: '#BBC6CD',
      btnBgGhostPressed: '#BBC6CD',
      btnTextGhost: '#062B3F',
      btnBgDisabled: '#F7F7F7',
      btnTextDisabled: '#626E81',
      border: '#BBC6CD',
      borderAccent: '#CC4E0A',
      borderInverse: '#FFFFFF',
      borderSuccess: '#267C51',
      borderWarning: '#F6BB33',
      borderError: '#D42D02',
      borderInformation: '#00BCDA',
      borderBrand: '#CCF2F8',
      borderWidthSm: 1,
      borderWidthMd: 2,
      borderWidthLg: 3,
      layer: '#FFFFFF',
      bgOverlay: '#062B3F',
      cardBackground: '#FFFFFF',
      popover: '#062B3F',
      focusBorder: '#062B3F',
      focusRingWidth: 1,
      focusRingOffset: 2,
      elevationXsColor: '#040C10',
      elevationXsBlur: 2,
      elevationXsOffsetY: 1,
      elevationSmColor: '#040C10',
      elevationSmBlur: 4,
      elevationSmOffsetY: 2,
      elevationMdColor: '#040C10',
      elevationMdBlur: 8,
      elevationMdOffsetY: 4,
      elevationLgColor: '#040C10',
      elevationLgBlur: 16,
      elevationLgOffsetY: 8,
      elevationXlColor: '#040C10',
      elevationXlBlur: 32,
      elevationXlOffsetY: 12,
      stepBgActive: '#062B3F',
      stepBgDone: '#062B3F',
      stepBgInactive: '#BBC6CD',
      stepBgError: '#D42D02',
      fontFamilyPrimary: 'Bouygues Speak Corpo',
      fontFamilySecondary: 'Bouygues Read',
    },
  },
  fonts: {
    sizeTitle1: 28,
    lineHeightTitle1: 36,
    fontTitle1: 'Bouygues Read',
    fontWeightTitle1: 400,
    sizeTitle2: 24,
    lineHeightTitle2: 30,
    fontTitle2: 'Bouygues Read',
    fontWeightTitle2: 400,
    sizeTitle3: 22,
    lineHeightTitle3: 28,
    fontTitle3: 'Bouygues Speak Corpo',
    fontWeightTitle3: 700,
    title4Size: 20,
    lineHeightTitle4: 26,
    fontTitle4: 'Bouygues Speak Corpo',
    fontWeightTitle4: 700,
    sizeTitle5: 18,
    lineHeightTitle5: 22,
    fontTitle5: 'Bouygues Speak Corpo',
    fontWeightTitle5: 700,
    sizeTitle6: 16,
    lineHeightTitle6: 20,
    fontTitle6: 'Bouygues Speak Corpo',
    fontWeightTitle6: 700,
    body1Size: 16,
    body1LineHeight: 24,
    fontBody1: 'Bouygues Speak Corpo',
    fontWeightBody1: 400,
    tokenfontBody1BoldSize: 16,
    tokenfontBody1BoldLineHeight: 24,
    tokenfontBody1BoldFontBody1Bold: 'Bouygues Speak Corpo',
    fontWeightBody1Bold: 600,
    body2Size: 14,
    body2LineHeight: 22,
    fontBody2: 'Bouygues Speak Corpo',
    fontWeightBody2: 400,
    tokenfontBody2BoldSize: 14,
    tokenfontBody2BoldLineHeight: 22,
    tokenfontBody2BoldFontBody2Bold: 'Bouygues Speak Corpo',
    fontWeightBody2Bold: 600,
    body3Size: 12,
    body3LineHeight: 18,
    fontBody3: 'Bouygues Speak Corpo',
    fontWeightBody3: 400,
    tokenfontBody3BoldSize: 12,
    tokenfontBody3BoldLineHeight: 18,
    tokenfontBody3BoldFontBody3Bold: 'Bouygues Speak Corpo',
    fontWeightBody3Bold: 600,
    body4Size: 10,
    body4LineHeight: 16,
    fontBody4: 'Bouygues Speak Corpo',
    fontWeightBody4: 400,
    tokenfontBody4BoldSize: 10,
    tokenfontBody4BoldLineHeight: 16,
    tokenfontBody4BoldFontBody4Bold: 'Bouygues Speak Corpo',
    fontWeightBody4Bold: 600,
  },
  radius: {
    radiusFull: 9999,
    radiusLg: 24,
    radiusMd: 16,
    radiusSm: 8,
    radiusXs: 4,
    radiusNone: 0,
  },
  spacings: {
    spacingXxxl: 40,
    spacingXxl: 40,
    spacingXl: 32,
    spacingLg: 24,
    spacingMd: 16,
    spacingSm: 12,
    spacingXs: 8,
    spacingXxs: 4,
    spacingNone: 0,
  },
} as const

export const THEMES_TRILOGY = {
  trilogy: THEME_TRILOGY,
} as const

export const THEME_COLORS_TRILOGY = THEME_TRILOGY.colors
export const THEME_FONTS_TRILOGY = THEME_TRILOGY.fonts
export const THEME_RADIUS_TRILOGY = THEME_TRILOGY.radius
export const THEME_SPACINGS_TRILOGY = THEME_TRILOGY.spacings
