import { THEME_TRILOGY } from '@trilogy-ds/react/theme'
import { StyleSheet } from 'react-native'

export const lightBackgroundStyles = StyleSheet.create({
  INFORMATION: { backgroundColor: THEME_TRILOGY.colors.light.bgInformation },
  INFORMATION_SUBTLE: { backgroundColor: THEME_TRILOGY.colors.light.bgInformationSubtle },
  SUCCESS: { backgroundColor: THEME_TRILOGY.colors.light.bgSuccess },
  SUCCESS_SUBTLE: { backgroundColor: THEME_TRILOGY.colors.light.bgSuccessSubtle },
  WARNING: { backgroundColor: THEME_TRILOGY.colors.light.bgWarning },
  WARNING_SUBTLE: { backgroundColor: THEME_TRILOGY.colors.light.bgWarningSubtle },
  ERROR: { backgroundColor: THEME_TRILOGY.colors.light.bgError },
  ERROR_SUBTLE: { backgroundColor: THEME_TRILOGY.colors.light.bgErrorSubtle },
  PRIMARY: { backgroundColor: THEME_TRILOGY.colors.light.bgPrimary },
  PRIMARY_SUBTLE: { backgroundColor: THEME_TRILOGY.colors.light.bgPrimarySubtle },
  SECONDARY: { backgroundColor: THEME_TRILOGY.colors.light.bgSecondary },
  SECONDARY_SUBTLE: { backgroundColor: THEME_TRILOGY.colors.light.bgSecondarySubtle },
  ACCENT: { backgroundColor: THEME_TRILOGY.colors.light.bgAccent },
  ACCENT_SUBTLE: { backgroundColor: THEME_TRILOGY.colors.light.bgAccentSubtle },
  BRAND: { backgroundColor: THEME_TRILOGY.colors.light.bgBrand },
  BRAND_SUBTLE: { backgroundColor: THEME_TRILOGY.colors.light.bgBrandSubtle },
  DISABLED: { backgroundColor: THEME_TRILOGY.colors.light.bgDisabled },
  SELECTED: { backgroundColor: THEME_TRILOGY.colors.light.bgSelected },
  SELECTED_HOVER: { backgroundColor: THEME_TRILOGY.colors.light.bgSelectedHover },
  SELECTED_PRESSED: { backgroundColor: THEME_TRILOGY.colors.light.tokenbackgroundSelectedPressed },
  INACTIVE: { backgroundColor: THEME_TRILOGY.colors.light.bgInactive },
  TRANSPARENT: { backgroundColor: 'transparent' },
})

export const darkBackgroundStyles = StyleSheet.create({
  INFORMATION: { backgroundColor: THEME_TRILOGY.colors.dark.bgInformation },
  INFORMATION_SUBTLE: { backgroundColor: THEME_TRILOGY.colors.dark.bgInformationSubtle },
  SUCCESS: { backgroundColor: THEME_TRILOGY.colors.dark.bgSuccess },
  SUCCESS_SUBTLE: { backgroundColor: THEME_TRILOGY.colors.dark.bgSuccessSubtle },
  WARNING: { backgroundColor: THEME_TRILOGY.colors.dark.bgWarning },
  WARNING_SUBTLE: { backgroundColor: THEME_TRILOGY.colors.dark.bgWarningSubtle },
  ERROR: { backgroundColor: THEME_TRILOGY.colors.dark.bgError },
  ERROR_SUBTLE: { backgroundColor: THEME_TRILOGY.colors.dark.bgErrorSubtle },
  PRIMARY: { backgroundColor: THEME_TRILOGY.colors.dark.bgPrimary },
  PRIMARY_SUBTLE: { backgroundColor: THEME_TRILOGY.colors.dark.bgPrimarySubtle },
  SECONDARY: { backgroundColor: THEME_TRILOGY.colors.dark.bgSecondary },
  SECONDARY_SUBTLE: { backgroundColor: THEME_TRILOGY.colors.dark.bgSecondarySubtle },
  ACCENT: { backgroundColor: THEME_TRILOGY.colors.dark.bgAccent },
  ACCENT_SUBTLE: { backgroundColor: THEME_TRILOGY.colors.dark.bgAccentSubtle },
  BRAND: { backgroundColor: THEME_TRILOGY.colors.dark.bgBrand },
  BRAND_SUBTLE: { backgroundColor: THEME_TRILOGY.colors.dark.bgBrandSubtle },
  DISABLED: { backgroundColor: THEME_TRILOGY.colors.dark.bgDisabled },
  SELECTED: { backgroundColor: THEME_TRILOGY.colors.dark.bgSelected },
  SELECTED_HOVER: { backgroundColor: THEME_TRILOGY.colors.dark.bgSelectedHover },
  SELECTED_PRESSED: { backgroundColor: THEME_TRILOGY.colors.dark.tokenbackgroundSelectedPressed },
  INACTIVE: { backgroundColor: THEME_TRILOGY.colors.dark.bgInactive },
  TRANSPARENT: { backgroundColor: 'transparent' },
})
