import { RadioProps, RadioRef } from '@/components/radio/RadioProps'
import { useTrilogyContext } from '@/context'
import { hashClass } from '@/helpers/hashClassesHelpers'
import clsx from 'clsx'
import React from 'react'
import { ComponentName } from '../enumsComponentsName'

/**
 * Radio Component
 * @param checked {boolean} Checked radio
 * @param disabled {boolean} Disabled radio
 * @param readonly {boolean} Read-only radio
 * @param id {string} Radio id (auto-generated by default)
 * @param label {string} Label for radio
 * @param onChange {RadioChangeEventHandler} onChange Event
 * @param name {string} Name for radio
 * @param value {string} Value for radio
 * @param testId {string} Test Id for Test Integration
 * - -------------------------- WEB PROPERTIES -------------------------------
 * @param className {string} Additional CSS Classes
 * @param required {boolean} Required radio
 */
const Radio = React.forwardRef<RadioRef, RadioProps>(
  (
    {
      checked,
      className,
      disabled,
      readonly,
      id = React.useId(),
      label,
      onChange,
      name,
      value,
      required,
      testId,
      ...others
    },
    ref,
  ): JSX.Element => {
    const { styled } = useTrilogyContext()

    return (
      <div ref={ref} className={hashClass(styled, clsx('radio', className))}>
        <input
          data-testid={testId}
          type='radio'
          readOnly={readonly}
          id={id}
          disabled={disabled}
          name={name}
          value={value}
          checked={checked}
          required={required}
          onChange={(e) => {
            if (onChange && !disabled && !readonly) {
              onChange(
                Object.assign(e, {
                  radioId: e.target.id,
                  radioValue: e.target.value,
                  radioName: e.target.name,
                  radioChecked: e.target.checked,
                }),
              )
            }
          }}
          {...others}
        />
        <label htmlFor={id} className={hashClass(styled, clsx('radio-label'))}>
          {label}
        </label>
      </div>
    )
  },
)

Radio.displayName = ComponentName.Radio
export default Radio
