import { ComponentName } from '@/components/enumsComponentsName'
import { RadioNativeProps, RadioNativeRef } from '@/components/radio/RadioProps'
import { Text } from '@/components/text'
import React from 'react'
import { StyleSheet, TouchableOpacity, View } from 'react-native'
import { getColorStyle } from "@/helpers/color";
import { TrilogyColor } from "@/interfaces/Color";
import { getRadiusStyle } from "@/helpers/radius";
import { Radius } from "@/interfaces/Radius";

/**
 * Radio Component
 * @param checked {boolean} Checked radio
 * @param disabled {boolean} Disabled radio
 * @param readonly {boolean} Readonly radio
 * @param id {string} Radio id (auto-generated by default)
 * @param label {string} Label for radio
 * @param onChange {RadioChangeEventHandlerNative} onChange Event
 * @param name {string} Name for radio
 * @param value {string} Value for radio
 */
const Radio = React.forwardRef<RadioNativeRef, RadioNativeProps>(
  ({ id = React.useId(), checked, name, onChange, disabled, readonly, label, value }, ref): JSX.Element => {
    const borderFullRadius = getRadiusStyle(Radius.FULL)
    const styles = StyleSheet.create({
      container: {
        flexDirection: 'row',
        alignItems: 'center',
      },
      radio: {
        alignItems: 'center',
        justifyContent: 'center',
        borderColor: getColorStyle(
          disabled ? TrilogyColor.DISABLED : checked ? TrilogyColor.MAIN : TrilogyColor.STROKE,
        ),
        borderWidth: 1,
        width: 18,
        height: 18,
        borderRadius: borderFullRadius,
        marginRight: 10,
      },
      icon: {
        borderRadius: borderFullRadius,
        width: 12,
        height: 12,
        backgroundColor: getColorStyle(TrilogyColor.MAIN),
      },
      label: {
        paddingTop: 2,
        color:
          (disabled && getColorStyle(TrilogyColor.DISABLED)) ||
          (checked && getColorStyle(TrilogyColor.MAIN)) ||
          getColorStyle(TrilogyColor.MAIN),
      },
    })

    const handleClick = (value: string) => {
      if (!readonly) {
        if (onChange) {
          onChange({
            radioId: id,
            radioValue: value,
            radioName: name || '',
            radioChecked: true,
          })
        }
      }
    }

    return (
      <TouchableOpacity ref={ref} disabled={disabled} style={styles.container} onPress={() => handleClick(value ?? '')}>
        <View style={styles.radio} testID={id}>
          {checked && <View style={styles.icon} />}
        </View>
        {label && typeof label.valueOf() === 'string' ? <Text style={styles.label}>{String(label)}</Text> : label}
      </TouchableOpacity>
    )
  },
)

Radio.displayName = ComponentName.Radio

export default Radio
