export { default as TableBody } from '@/components/table/body/TableBody'
export { default as TableHead } from '@/components/table/head/TableHead'
export { default as Table } from '@/components/table/Table'
export { default as TableTd } from '@/components/table/td/TableTd'
export { default as TableTh } from '@/components/table/th/TableTh'
export { default as TableTr } from '@/components/table/tr/TableTr'
