import { defineConfig } from 'tsup'

export default defineConfig({
  clean: true,
  target: 'es2019',
  format: ['cjs', 'esm'],
  outDir: 'lib',
  banner: { js: '"use client";' },
  entry: [
    '.',
    '!./components/**/*.stories.tsx',
    '!./components/**/test',
    '!./scripts',
    '!node_modules',
    '!tsconfig.*',
    '!*.md',
    '!./lib',
    '!version.json',
    '!babel.config.cjs',
    '!custom.d.ts',
    '!jest*',
    '!tsup.config.ts',
    '!package.json',
    '!snapshotResolver.ts',
    '!coverage',
  ],
  external: ['react', 'react-native', 'react-dom'],
  tsconfig: './tsconfig.build.json',
  dts: true,
})
