import { useTrilogyContext } from '@/context'
import { hashClass } from '@/helpers/hashClassesHelpers'
import clsx from 'clsx'
import { ChangeEvent, forwardRef, useCallback, useEffect, useId, useState } from 'react'
import { ComponentName } from '@/components/enumsComponentsName'
import { CheckboxProps, CheckboxRef } from '@/components/checkbox/CheckboxProps'

/**
 * Checkbox Component
 * @param checked {boolean} Checked Checkbox
 * @param disabled {boolean} Disabled
 * @param readonly {boolean} Readonly Checkbox
 * @param id {string} Checkbox id (auto-generated by default)
 * @param label {string} Label for Checkbox (incompatible with children)
 * @param children {ReactNode} Children for Checkbox (incompatible with label)
 * @param onChange {Function} onChange Event
 * @param name {string} Name for checkbox
 * @param testId {string} Test Id for Test Integration
 * - -------------------------- WEB PROPERTIES -------------------------------
 * @param value {string} Value for checkbox
 * @param className {string} Additional CSS Classes
 * @param required {boolean} Required checkbox
 */
const Checkbox = forwardRef<CheckboxRef, CheckboxProps>(
  (
    { checked, className, disabled, readonly, id, label, onChange, name, value, children, required, testId, ...others },
    ref,
  ): JSX.Element => {
    const generateId = useId()
    const { styled } = useTrilogyContext()
    const [_checked, setChecked] = useState<boolean>(checked || false)

    useEffect(() => {
      if (!readonly) {
        setChecked(checked || false)
      }
    }, [checked, readonly])

    const handleOnChange = useCallback(
      (e: ChangeEvent<HTMLInputElement>): void => {
        const { target } = e
        if (onChange) {
          onChange({
            checkboxId: target.id,
            checkboxValue: target.value,
            checkboxName: target.name,
            checkboxChecked: target.checked,
          })
        } else {
          setChecked(target.checked)
        }
      },
      [onChange],
    )

    return (
      <div ref={ref} className={hashClass(styled, clsx('checkbox', className))}>
        <input
          data-testid={testId}
          type='checkbox'
          readOnly={readonly}
          id={id ?? generateId}
          required={required}
          disabled={disabled}
          name={name}
          value={value}
          checked={readonly ? checked : _checked}
          onChange={handleOnChange}
          {...others}
        />
        <label htmlFor={id ?? generateId} className={hashClass(styled, clsx('checkbox-label'))}>
          {label ?? children}
        </label>
      </div>
    )
  },
)

Checkbox.displayName = ComponentName.Checkbox
export default Checkbox
